name: shared_code
description: This is the shared code in the shiaka projects
version: 0.0.4
homepage: https://github.com/amrmhassan/shared_code

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  image_picker_platform_interface: ^2.9.3
  json_annotation: ^4.8.1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  copy_with_extension_gen: ^4.0.0



flutter:
  assets:
    - assets/icons/
    - assets/svg/